CREATE TABLE IF NOT EXISTS warehouse.dim_date (
    date_key       INTEGER PRIMARY KEY,
    full_date      DATE NOT NULL UNIQUE,
    day_of_month   SMALLINT NOT NULL,
    day_of_week    SMALLINT NOT NULL,
    day_name       VARCHAR(10) NOT NULL,
    week_of_year   SMALLINT NOT NULL,
    month_number   SMALLINT NOT NULL,
    month_name     VARCHAR(10) NOT NULL,
    quarter_number SMALLINT NOT NULL,
    year_number    SMALLINT NOT NULL,
    is_weekend     BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouse.dim_customer (
    customer_key             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id              TEXT NOT NULL UNIQUE,
    customer_unique_id       TEXT,
    zip_code_prefix          INTEGER,
    city                     TEXT,
    state                    TEXT,
    latitude                 DOUBLE PRECISION,
    longitude                DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS warehouse.dim_product (
    product_key                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id                  TEXT NOT NULL UNIQUE,
    category_name               TEXT,
    category_name_english       TEXT,
    product_name_length         INTEGER,
    product_description_length  INTEGER,
    product_photos_quantity     INTEGER,
    product_weight_g            NUMERIC(12, 2),
    product_length_cm           NUMERIC(12, 2),
    product_height_cm           NUMERIC(12, 2),
    product_width_cm            NUMERIC(12, 2)
);

CREATE TABLE IF NOT EXISTS warehouse.dim_seller (
    seller_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id        TEXT NOT NULL UNIQUE,
    zip_code_prefix  INTEGER,
    city             TEXT,
    state            TEXT,
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS warehouse.fact_order_items (
    order_item_key      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id            TEXT NOT NULL,
    order_item_id       INTEGER NOT NULL,
    customer_key        BIGINT NOT NULL REFERENCES warehouse.dim_customer(customer_key),
    product_key         BIGINT NOT NULL REFERENCES warehouse.dim_product(product_key),
    seller_key          BIGINT NOT NULL REFERENCES warehouse.dim_seller(seller_key),
    order_date_key      INTEGER NOT NULL REFERENCES warehouse.dim_date(date_key),
    shipping_date_key   INTEGER REFERENCES warehouse.dim_date(date_key),
    quantity            INTEGER NOT NULL DEFAULT 1,
    item_price          NUMERIC(12, 2) NOT NULL,
    freight_value       NUMERIC(12, 2) NOT NULL,
    total_item_value    NUMERIC(12, 2) NOT NULL,
    UNIQUE (order_id, order_item_id)
);

CREATE TABLE IF NOT EXISTS warehouse.fact_payments (
    payment_key          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id             TEXT NOT NULL,
    payment_sequential   INTEGER NOT NULL,
    customer_key         BIGINT NOT NULL REFERENCES warehouse.dim_customer(customer_key),
    payment_date_key     INTEGER NOT NULL REFERENCES warehouse.dim_date(date_key),
    payment_type         TEXT NOT NULL,
    installment_count    INTEGER,
    payment_value        NUMERIC(12, 2) NOT NULL,
    UNIQUE (order_id, payment_sequential)
);

CREATE TABLE IF NOT EXISTS warehouse.fact_order_lifecycle (
    order_key                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id                        TEXT NOT NULL UNIQUE,
    customer_key                    BIGINT NOT NULL REFERENCES warehouse.dim_customer(customer_key),
    purchase_date_key               INTEGER NOT NULL REFERENCES warehouse.dim_date(date_key),
    approved_date_key               INTEGER REFERENCES warehouse.dim_date(date_key),
    delivered_date_key              INTEGER REFERENCES warehouse.dim_date(date_key),
    estimated_delivery_date_key     INTEGER REFERENCES warehouse.dim_date(date_key),
    order_status                    TEXT NOT NULL,
    order_purchase_timestamp        TIMESTAMP NOT NULL,
    order_approved_at               TIMESTAMP,
    order_delivered_customer_date   TIMESTAMP,
    order_estimated_delivery_date   TIMESTAMP,
    item_count                      INTEGER NOT NULL,
    merchandise_value               NUMERIC(14, 2) NOT NULL,
    freight_value                   NUMERIC(14, 2) NOT NULL,
    payment_value                   NUMERIC(14, 2) NOT NULL,
    approval_duration_minutes       NUMERIC(14, 2),
    delivery_duration_hours         NUMERIC(14, 2),
    delivery_delay_days             NUMERIC(14, 2),
    is_delivered_late               BOOLEAN,
    is_cancelled                    BOOLEAN NOT NULL
);

TRUNCATE TABLE
    warehouse.fact_order_items,
    warehouse.fact_payments,
    warehouse.fact_order_lifecycle,
    warehouse.dim_customer,
    warehouse.dim_product,
    warehouse.dim_seller,
    warehouse.dim_date
RESTART IDENTITY CASCADE;

INSERT INTO warehouse.dim_date (
    date_key, full_date, day_of_month, day_of_week, day_name, week_of_year,
    month_number, month_name, quarter_number, year_number, is_weekend
)
WITH all_source_dates AS (
    SELECT order_purchase_timestamp::DATE AS source_date FROM staging.stg_orders
    UNION ALL
    SELECT order_approved_at::DATE FROM staging.stg_orders
    UNION ALL
    SELECT order_delivered_carrier_date::DATE FROM staging.stg_orders
    UNION ALL
    SELECT order_delivered_customer_date::DATE FROM staging.stg_orders
    UNION ALL
    SELECT order_estimated_delivery_date::DATE FROM staging.stg_orders
    UNION ALL
    SELECT shipping_limit_date::DATE FROM staging.stg_order_items
),
date_boundaries AS (
    SELECT MIN(source_date) AS min_date, MAX(source_date) AS max_date
    FROM all_source_dates
    WHERE source_date IS NOT NULL
)
SELECT
    TO_CHAR(calendar_date, 'YYYYMMDD')::INTEGER,
    calendar_date,
    EXTRACT(DAY FROM calendar_date)::SMALLINT,
    EXTRACT(ISODOW FROM calendar_date)::SMALLINT,
    TRIM(TO_CHAR(calendar_date, 'Day')),
    EXTRACT(WEEK FROM calendar_date)::SMALLINT,
    EXTRACT(MONTH FROM calendar_date)::SMALLINT,
    TRIM(TO_CHAR(calendar_date, 'Month')),
    EXTRACT(QUARTER FROM calendar_date)::SMALLINT,
    EXTRACT(YEAR FROM calendar_date)::SMALLINT,
    EXTRACT(ISODOW FROM calendar_date) IN (6, 7)
FROM GENERATE_SERIES(
    (SELECT min_date FROM date_boundaries),
    (SELECT max_date FROM date_boundaries),
    INTERVAL '1 day'
) AS dates(calendar_date);

INSERT INTO warehouse.dim_customer (
    customer_key, customer_id, customer_unique_id, zip_code_prefix,
    city, state, latitude, longitude
)
VALUES (-1, 'UNKNOWN', 'UNKNOWN', NULL, 'Unknown', 'Unknown', NULL, NULL);

INSERT INTO warehouse.dim_customer (
    customer_id, customer_unique_id, zip_code_prefix, city, state, latitude, longitude
)
SELECT
    c.customer_id,
    c.customer_unique_id,
    c.customer_zip_code_prefix,
    c.customer_city,
    c.customer_state,
    g.latitude,
    g.longitude
FROM staging.stg_customers c
LEFT JOIN staging.stg_geolocation g
    ON c.customer_zip_code_prefix = g.geolocation_zip_code_prefix;

INSERT INTO warehouse.dim_product (
    product_key, product_id, category_name, category_name_english
)
VALUES (-1, 'UNKNOWN', 'Unknown', 'Unknown');

INSERT INTO warehouse.dim_product (
    product_id, category_name, category_name_english, product_name_length,
    product_description_length, product_photos_quantity, product_weight_g,
    product_length_cm, product_height_cm, product_width_cm
)
SELECT
    p.product_id,
    p.product_category_name,
    COALESCE(t.product_category_name_english, p.product_category_name),
    p.product_name_length,
    p.product_description_length,
    p.product_photos_quantity,
    p.product_weight_g,
    p.product_length_cm,
    p.product_height_cm,
    p.product_width_cm
FROM staging.stg_products p
LEFT JOIN staging.stg_category_translation t
    ON p.product_category_name = t.product_category_name;

INSERT INTO warehouse.dim_seller (
    seller_key, seller_id, zip_code_prefix, city, state, latitude, longitude
)
VALUES (-1, 'UNKNOWN', NULL, 'Unknown', 'Unknown', NULL, NULL);

INSERT INTO warehouse.dim_seller (
    seller_id, zip_code_prefix, city, state, latitude, longitude
)
SELECT
    s.seller_id,
    s.seller_zip_code_prefix,
    s.seller_city,
    s.seller_state,
    g.latitude,
    g.longitude
FROM staging.stg_sellers s
LEFT JOIN staging.stg_geolocation g
    ON s.seller_zip_code_prefix = g.geolocation_zip_code_prefix;

INSERT INTO warehouse.fact_order_items (
    order_id, order_item_id, customer_key, product_key, seller_key,
    order_date_key, shipping_date_key, quantity, item_price, freight_value,
    total_item_value
)
SELECT
    i.order_id,
    i.order_item_id,
    COALESCE(c.customer_key, -1),
    COALESCE(p.product_key, -1),
    COALESCE(s.seller_key, -1),
    TO_CHAR(o.order_purchase_timestamp, 'YYYYMMDD')::INTEGER,
    TO_CHAR(i.shipping_limit_date, 'YYYYMMDD')::INTEGER,
    1,
    i.price,
    i.freight_value,
    i.price + i.freight_value
FROM staging.stg_order_items i
JOIN staging.stg_orders o ON i.order_id = o.order_id
LEFT JOIN warehouse.dim_customer c ON o.customer_id = c.customer_id
LEFT JOIN warehouse.dim_product p ON i.product_id = p.product_id
LEFT JOIN warehouse.dim_seller s ON i.seller_id = s.seller_id;

INSERT INTO warehouse.fact_payments (
    order_id, payment_sequential, customer_key, payment_date_key,
    payment_type, installment_count, payment_value
)
SELECT
    p.order_id,
    p.payment_sequential,
    COALESCE(c.customer_key, -1),
    TO_CHAR(o.order_purchase_timestamp, 'YYYYMMDD')::INTEGER,
    p.payment_type,
    p.payment_installments,
    p.payment_value
FROM staging.stg_payments p
JOIN staging.stg_orders o ON p.order_id = o.order_id
LEFT JOIN warehouse.dim_customer c ON o.customer_id = c.customer_id;

WITH item_totals AS (
    SELECT
        order_id,
        COUNT(*)::INTEGER AS item_count,
        SUM(price)::NUMERIC(14, 2) AS merchandise_value,
        SUM(freight_value)::NUMERIC(14, 2) AS freight_value
    FROM staging.stg_order_items
    GROUP BY order_id
),
payment_totals AS (
    SELECT
        order_id,
        SUM(payment_value)::NUMERIC(14, 2) AS payment_value
    FROM staging.stg_payments
    GROUP BY order_id
)
INSERT INTO warehouse.fact_order_lifecycle (
    order_id, customer_key, purchase_date_key, approved_date_key,
    delivered_date_key, estimated_delivery_date_key, order_status,
    order_purchase_timestamp, order_approved_at, order_delivered_customer_date,
    order_estimated_delivery_date, item_count, merchandise_value, freight_value,
    payment_value, approval_duration_minutes, delivery_duration_hours,
    delivery_delay_days, is_delivered_late, is_cancelled
)
SELECT
    o.order_id,
    COALESCE(c.customer_key, -1),
    TO_CHAR(o.order_purchase_timestamp, 'YYYYMMDD')::INTEGER,
    TO_CHAR(o.order_approved_at, 'YYYYMMDD')::INTEGER,
    TO_CHAR(o.order_delivered_customer_date, 'YYYYMMDD')::INTEGER,
    TO_CHAR(o.order_estimated_delivery_date, 'YYYYMMDD')::INTEGER,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    COALESCE(i.item_count, 0),
    COALESCE(i.merchandise_value, 0),
    COALESCE(i.freight_value, 0),
    COALESCE(p.payment_value, 0),
    EXTRACT(EPOCH FROM (o.order_approved_at - o.order_purchase_timestamp)) / 60,
    EXTRACT(EPOCH FROM (o.order_delivered_customer_date - o.order_purchase_timestamp)) / 3600,
    EXTRACT(EPOCH FROM (
        o.order_delivered_customer_date - o.order_estimated_delivery_date
    )) / 86400,
    CASE
        WHEN o.order_delivered_customer_date IS NULL THEN NULL
        ELSE o.order_delivered_customer_date > o.order_estimated_delivery_date
    END,
    o.order_status = 'canceled'
FROM staging.stg_orders o
LEFT JOIN warehouse.dim_customer c ON o.customer_id = c.customer_id
LEFT JOIN item_totals i ON o.order_id = i.order_id
LEFT JOIN payment_totals p ON o.order_id = p.order_id;
